version: '3.9'

services:
  app:
    build:
      context: . # use current dir
      args:
        - DEV=true
    ports:
      - "8000:8000" # mapping port 8000 local nachine to port 8000 inside Docker container
    volumes:
      - ./app:/app # mapping the app dir that created in the project to Ford's hash app inside Docker container
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=123123
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data # mapping dir in container to local - to persistent data
    environment: # to set the init db config for new db service
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"

volumes:
  dev-db-data: